export const LANGUAGE_OPTIONS = [
  { label: 'English (en)', value: 'en' },
  { label: 'English (UK) (en_GB)', value: 'en_GB' },
  { label: 'English (US) (en_US)', value: 'en_US' },
  { label: 'English (UAE) (en_AE)', value: 'en_AE' },
  { label: 'English (AUS) (en_AU)', value: 'en_AU' },
  { label: 'English (CAN) (en_CA)', value: 'en_CA' },
  { label: 'English (GHA) (en_GH)', value: 'en_GH' },
  { label: 'English (IRL) (en_IE)', value: 'en_IE' },
  { label: 'English (IND) (en_IN)', value: 'en_IN' },
  { label: 'English (JAM) (en_JM)', value: 'en_JM' },
  { label: 'English (MYS) (en_MY)', value: 'en_MY' },
  { label: 'English (NZL) (en_NZ)', value: 'en_NZ' },
  { label: 'English (QAT) (en_QA)', value: 'en_QA' },
  { label: 'English (SGP) (en_SG)', value: 'en_SG' },
  { label: 'English (UGA) (en_UG)', value: 'en_UG' },
  { label: 'English (ZAF) (en_ZA)', value: 'en_ZA' },
  { label: 'Spanish (es)', value: 'es' },
  { label: 'Spanish (ARG) (es_AR)', value: 'es_AR' },
  { label: 'Spanish (CHL) (es_CL)', value: 'es_CL' },
  { label: 'Spanish (COL) (es_CO)', value: 'es_CO' },
  { label: 'Spanish (CRI) (es_CR)', value: 'es_CR' },
  { label: 'Spanish (DOM) (es_DO)', value: 'es_DO' },
  { label: 'Spanish (ECU) (es_EC)', value: 'es_EC' },
  { label: 'Spanish (HND) (es_HN)', value: 'es_HN' },
  { label: 'Spanish (MEX) (es_MX)', value: 'es_MX' },
  { label: 'Spanish (PAN) (es_PA)', value: 'es_PA' },
  { label: 'Spanish (PER) (es_PE)', value: 'es_PE' },
  { label: 'Spanish (SPA) (es_ES)', value: 'es_ES' },
  { label: 'Spanish (URY) (es_UY)', value: 'es_UY' },
  { label: 'Afrikaans (af)', value: 'af' },
  { label: 'Albanian (sq)', value: 'sq' },
  { label: 'Arabic (ar)', value: 'ar' },
  { label: 'Arabic (EGY) (ar_EG)', value: 'ar_EG' },
  { label: 'Arabic (UAE) (ar_AE)', value: 'ar_AE' },
  { label: 'Arabic (LBN) (ar_LB)', value: 'ar_LB' },
  { label: 'Arabic (MAR) (ar_MA)', value: 'ar_MA' },
  { label: 'Arabic (QAT) (ar_QA)', value: 'ar_QA' },
  { label: 'Azerbaijani (az)', value: 'az' },
  { label: 'Belarusian (be_BY)', value: 'be_BY' },
  { label: 'Bengali (bn)', value: 'bn' },
  { label: 'Bengali (IND) (bn_IN)', value: 'bn_IN' },
  { label: 'Bulgarian (bg)', value: 'bg' },
  { label: 'Catalan (ca)', value: 'ca' },
  { label: 'Chinese (CHN) (zh_CN)', value: 'zh_CN' },
  { label: 'Chinese (HKG) (zh_HK)', value: 'zh_HK' },
  { label: 'Chinese (TAI) (zh_TW)', value: 'zh_TW' },
  { label: 'Croatian (hr)', value: 'hr' },
  { label: 'Czech (cs)', value: 'cs' },
  { label: 'Danish (da)', value: 'da' },
  { label: 'Dari (prs_AF)', value: 'prs_AF' },
  { label: 'Dutch (nl)', value: 'nl' },
  { label: 'Dutch (BEL) (nl_BE)', value: 'nl_BE' },
  { label: 'Estonian (et)', value: 'et' },
  { label: 'Filipino (fil)', value: 'fil' },
  { label: 'Finnish (fi)', value: 'fi' },
  { label: 'French (fr)', value: 'fr' },
  { label: 'French (BEL) (fr_BE)', value: 'fr_BE' },
  { label: 'French (CAN) (fr_CA)', value: 'fr_CA' },
  { label: 'French (CHE) (fr_CH)', value: 'fr_CH' },
  { label: 'French (CIV) (fr_CI)', value: 'fr_CI' },
  { label: 'French (MAR) (fr_MA)', value: 'fr_MA' },
  { label: 'Georgian (ka)', value: 'ka' },
  { label: 'German (de)', value: 'de' },
  { label: 'German (AUT) (de_AT)', value: 'de_AT' },
  { label: 'German (CHE) (de_CH)', value: 'de_CH' },
  { label: 'Greek (el)', value: 'el' },
  { label: 'Gujarati (gu)', value: 'gu' },
  { label: 'Hausa (ha)', value: 'ha' },
  { label: 'Hebrew (he)', value: 'he' },
  { label: 'Hindi (hi)', value: 'hi' },
  { label: 'Hungarian (hu)', value: 'hu' },
  { label: 'Indonesian (id)', value: 'id' },
  { label: 'Irish (ga)', value: 'ga' },
  { label: 'Italian (it)', value: 'it' },
  { label: 'Japanese (ja)', value: 'ja' },
  { label: 'Kannada (kn)', value: 'kn' },
  { label: 'Kazakh (kk)', value: 'kk' },
  { label: 'Kinyarwanda (rw_RW)', value: 'rw_RW' },
  { label: 'Korean (ko)', value: 'ko' },
  { label: 'Kyrgyz (Kyrgyzstan) (ky_KG)', value: 'ky_KG' },
  { label: 'Lao (lo)', value: 'lo' },
  { label: 'Latvian (lv)', value: 'lv' },
  { label: 'Lithuanian (lt)', value: 'lt' },
  { label: 'Macedonian (mk)', value: 'mk' },
  { label: 'Malay (ms)', value: 'ms' },
  { label: 'Malayalam (ml)', value: 'ml' },
  { label: 'Marathi (mr)', value: 'mr' },
  { label: 'Norwegian (nb)', value: 'nb' },
  { label: 'Pashto (ps_AF)', value: 'ps_AF' },
  { label: 'Persian (fa)', value: 'fa' },
  { label: 'Polish (pl)', value: 'pl' },
  { label: 'Portuguese (BR) (pt_BR)', value: 'pt_BR' },
  { label: 'Portuguese (POR) (pt_PT)', value: 'pt_PT' },
  { label: 'Punjabi (pa)', value: 'pa' },
  { label: 'Romanian (ro)', value: 'ro' },
  { label: 'Russian (ru)', value: 'ru' },
  { label: 'Serbian (sr)', value: 'sr' },
  { label: 'Sinhala (si_LK)', value: 'si_LK' },
  { label: 'Slovak (sk)', value: 'sk' },
  { label: 'Slovenian (sl)', value: 'sl' },
  { label: 'Swahili (sw)', value: 'sw' },
  { label: 'Swedish (sv)', value: 'sv' },
  { label: 'Tamil (ta)', value: 'ta' },
  { label: 'Telugu (te)', value: 'te' },
  { label: 'Thai (th)', value: 'th' },
  { label: 'Turkish (tr)', value: 'tr' },
  { label: 'Ukrainian (uk)', value: 'uk' },
  { label: 'Urdu (ur)', value: 'ur' },
  { label: 'Uzbek (uz)', value: 'uz' },
  { label: 'Vietnamese (vi)', value: 'vi' },
  { label: 'Zulu (zu)', value: 'zu' },
];

export const CATEGORY_OPTIONS = [
  { label: 'Utility', value: 'UTILITY' },
  { label: 'Marketing', value: 'MARKETING' },
];

export const CATEGORY_LABELS: Record<string, string> = {
  UTILITY: 'Utility',
  MARKETING: 'Marketing',
};

export const FORMAT_LABELS: Record<string, string> = {
  TEXT: 'Text',
  IMAGE: 'Image',
  VIDEO: 'Video',
  DOCUMENT: 'Document',
};

export const LOCALE_LABELS: Record<string, string> = {
  en: 'English (en)',
  hi: 'Hindi (hi)',
  es: 'Spanish (es)',
  fr: 'French (fr)',
  de: 'German (de)',
  pt: 'Portuguese (pt)',
  ar: 'Arabic (ar)',
};

export const SMS_CATEGORY_LABELS: Record<string, string> = {
  service_implicit: 'Transactional',
  service_explicit: 'Engagement',
  promotional: 'Promotional',
};

export const CHANNEL_LABEL: Record<string, string> = {
  sms: 'SMS',
  whatsapp: 'WhatsApp',
};

export function variantLocaleToBase(locale: string): string {
  if (!locale) return '';
  const base = locale.split('_')[0].toLowerCase();
  if (LANGUAGE_OPTIONS.some((o) => o.value === locale)) return locale;
  if (LANGUAGE_OPTIONS.some((o) => o.value === base)) return base;
  return '';
}
